version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HOME=/opt/bitnami
      - PIP_CACHE_DIR=/opt/bitnami/.cache/pip
    ports:
      - '8080:8080'
    volumes:
      - ".:/files:rw"
    networks:
      - spark-mongo-network
    command: >
      /bin/bash -c "
      pip install --no-cache-dir pymongo &&
      /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master"

  spark-worker-1:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HOME=/opt/bitnami
      - PIP_CACHE_DIR=/opt/bitnami/.cache/pip
    volumes:
      - ".:/files:rw"
    networks:
      - spark-mongo-network
    command: >
      /bin/bash -c "
      pip install --no-cache-dir pymongo &&
      /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077"

  spark-worker-2:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HOME=/opt/bitnami
      - PIP_CACHE_DIR=/opt/bitnami/.cache/pip
    volumes:
      - ".:/files:rw"
    networks:
      - spark-mongo-network
    command: >
      /bin/bash -c "
      pip install --no-cache-dir pymongo &&
      /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077"

  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - '27017:27017'
    networks:
      - spark-mongo-network
    volumes:
      - mongodb-data:/data/db

networks:
  spark-mongo-network:
    driver: bridge

volumes:
  mongodb-data:
